# Generated by Django 5.2.2 on 2025-06-09 08:13

import converter.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(help_text='Upload Word document (.docx)', upload_to=converter.models.upload_to_input, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])])),
                ('output_file', models.FileField(blank=True, help_text='Generated PowerPoint file', null=True, upload_to=converter.models.upload_to_output)),
                ('template_type', models.CharField(choices=[('passage', 'Passage'), ('mcq1', 'MCQ Type 1'), ('mcq2', 'MCQ Type 2'), ('mcq3', 'MCQ Type 3')], help_text='Type of conversion template', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if conversion failed')),
                ('user_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent string', max_length=255)),
            ],
            options={
                'verbose_name': 'Conversion Job',
                'verbose_name_plural': 'Conversion Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
