# Generated by Django 5.2.2 on 2025-06-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionjob',
            name='template_type',
            field=models.CharField(choices=[('passage', 'English'), ('mcq1', 'Quantitative Ability Workshop Handout'), ('mcq2', 'Logical Ability Workshop Handout'), ('mcq3', 'Direction Sense for IBPS RRB PO & Clerk Prelim Exam')], help_text='Type of conversion template', max_length=20),
        ),
    ]
