# Generated by Django 5.2.2 on 2025-06-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_alter_conversionjob_template_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionjob',
            name='template_type',
            field=models.CharField(choices=[('passage', 'CLAT'), ('mcq1', 'Blank - QWH'), ('mcq2', 'Blank - LWH'), ('mcq3', 'YouTube')], help_text='Type of conversion template', max_length=20),
        ),
    ]
